# Generated by Django 5.2.1 on 2025-07-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad_actual', models.CharField(max_length=10)),
                ('humedad_maxima', models.CharField(max_length=10)),
                ('humedad_minima', models.CharField(max_length=10)),
                ('humedad_solicitada', models.CharField(max_length=10)),
            ],
        ),
    ]
