# Generated by Django 5.2.1 on 2025-05-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('NombreUsuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
    ]
