# Generated by Django 5.2.1 on 2025-05-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('agricola', 'Agricultor'), ('administrador', 'Administrador')], default=None, max_length=20),
        ),
    ]
