# Generated by Django 5.2.1 on 2025-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registro_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('agricola', 'Agricultor'), ('administrador', 'Administrador')], default='Seleccione su rol', max_length=20),
        ),
    ]
