# Generated by Django 5.2.1 on 2025-07-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_iniciosecion_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semillatipo',
            name='tipo_semilla',
            field=models.CharField(choices=[('Alverja', 'Alverja'), ('Frijoles', 'Frijoles'), ('Cafe', 'Cafe'), ('Sandia', 'Sandia'), ('Papa', 'Papa'), ('Aguacate', 'Aguacate'), ('Tomate', 'Tomate'), ('Mora', 'Mora'), ('Papaya', 'Papaya'), ('Uvas', 'Uvas')], max_length=1000),
        ),
    ]
