# Generated by Django 5.2.1 on 2025-05-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_registro_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('Agricultor', 'Agricultor'), ('Administrador', 'Administrador')], max_length=20),
        ),
    ]
