# Generated by Django 5.2.1 on 2025-05-24 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_registro_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registro')),
            ],
        ),
    ]
