# Generated by Django 5.2.1 on 2025-05-24 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_administrador_agricultor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contraseña',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nombreUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registro'),
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='contraseña',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='nombreUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registro'),
        ),
    ]
