# Generated by Django 5.2.1 on 2025-05-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_administrador_contraseña_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='InicioSecion',
        ),
        migrations.DeleteModel(
            name='Agricultor',
        ),
    ]
