# Generated by Django 5.2.1 on 2025-06-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_administrador_iniciosecion_delete_agricultor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('Agricultor', 'Agricultor'), ('Administrador', 'Administrador')], default='Seleccione su rol', max_length=20),
        ),
    ]
