# Generated by Django 5.2.1 on 2025-06-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_registro_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='contraseña',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
