# Generated by Django 5.2.1 on 2025-06-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_registro_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='admingestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.DateField()),
                ('Cantidad_Productos', models.CharField(max_length=10)),
                ('tipo_Cosecha', models.CharField(choices=[('Papa', 'Papa'), ('Aguacate', 'Aguacate'), ('Cafe', 'Cafe'), ('Sandia', 'Sandia')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='adminventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semillas', models.CharField(choices=[('Alverja', 'Alverja'), ('Frijoles', 'Frijoles'), ('Cafe', 'Cafe'), ('Sandia', 'Sandia')], max_length=10)),
                ('CosechasRegistradas', models.CharField(choices=[('Papa', 'Papa'), ('Aguacate', 'Aguacate'), ('Cafe', 'Cafe'), ('Sandia', 'Sandia')], max_length=10)),
                ('PerdidasRegistradas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GestioFechasAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporadas', models.CharField(choices=[('Temporada 1', 'Temporada 1'), ('Temporada 2', 'Temporada 2'), ('Temporada 3', 'Temporada 3'), ('Temporada 4', 'Temporada 4')], max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='reportesadministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activos_Registrados', models.BigIntegerField()),
                ('Pasivos_Registrados', models.BigIntegerField()),
                ('Gnanacias_Registradas', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CantidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('Tractores', 'Tractores'), ('Insectisida', 'Insectisida'), ('Semillas', 'Semillas'), ('Maquinaria', 'Maquinaria')], max_length=100)),
                ('cantidadesproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admingestion')),
            ],
        ),
        migrations.CreateModel(
            name='semillaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=1000)),
                ('tipo_semilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adminventario')),
            ],
        ),
        migrations.CreateModel(
            name='tipoCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(choices=[('Temporada 1', 'Temporada 1'), ('Temporada 2', 'Temporada 2'), ('Temporada 3', 'Temporada 3'), ('Temporada 4', 'Temporada 4')], max_length=100)),
                ('tipo_cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adminventario')),
            ],
        ),
    ]
