# Generated by Django 5.2.1 on 2025-06-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_adminventario_cosechasregistradas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocosecha',
            name='tipo_cosecha',
            field=models.CharField(choices=[('Papa', 'Papa'), ('Aguacate', 'Aguacate'), ('Cafe', 'Cafe'), ('Sandia', 'Sandia')], max_length=100),
        ),
    ]
