# Generated by Django 5.2.1 on 2025-06-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_tipocosecha_tipo_cosecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestiofechasadmin',
            name='fecha',
            field=models.DateField(),
        ),
    ]
