# Generated by Django 5.2.1 on 2025-07-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agro_Control', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agricultor',
        ),
        migrations.DeleteModel(
            name='CientificoDeDatos',
        ),
    ]
