# Generated by Django 5.2.1 on 2025-07-06 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('bateria', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conectado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fertilizante_usado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo_suelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('area_cubierta', models.CharField(max_length=100)),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_Drones.ejecucion')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('dron', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agro_Drones.dron')),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_Drones.terreno')),
            ],
        ),
        migrations.AddField(
            model_name='ejecucion',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_Drones.ruta'),
        ),
        migrations.CreateModel(
            name='ParametroFertilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cultivo', models.CharField(max_length=100)),
                ('tipo_fertilizante', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('zonas', models.TextField()),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_Drones.terreno')),
            ],
        ),
    ]
