# from django.urls import path
# from .views import RegistroGetViewSet,RegistroPostViewSet,RegistroUpdateViewSet,RegistroDeleteViewSet

# urlpatterns = [
#     # ---Registro---
#     path('registro', RegistroGetViewSet.as_view()),
#     path('registro', RegistroPostViewSet.as_view()),
#     path('registro', RegistroUpdateViewSet.as_view()),
#     path('registro', RegistroDeleteViewSet.as_view())
# ]
